// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsA6A5CBU_v5aKuSNEODjTkofHWRaL7sU',
    appId: '1:10138376114:web:01d93dc1de788397c2b6ab',
    messagingSenderId: '10138376114',
    projectId: 'vidis-31aaa',
    authDomain: 'vidis-31aaa.firebaseapp.com',
    storageBucket: 'vidis-31aaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01Eo1mWN0hJgX8r2AZroMseHsXo-c2G8',
    appId: '1:10138376114:android:a3fe5e98026cc2f8c2b6ab',
    messagingSenderId: '10138376114',
    projectId: 'vidis-31aaa',
    storageBucket: 'vidis-31aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC16Zm-NavHyHIGiTTHba98gPJvD8rqJPQ',
    appId: '1:10138376114:ios:dd18fbeacabc5beac2b6ab',
    messagingSenderId: '10138376114',
    projectId: 'vidis-31aaa',
    storageBucket: 'vidis-31aaa.appspot.com',
    iosBundleId: 'com.example.vidis',
  );
}
